import React, { useState, useEffect } from 'react';
import { FileText, Download, Trash2, Eye, MoreHorizontal, Plus, Loader2, CheckCircle } from 'lucide-react';
import { useNavigate } from 'react-router';
import { supabase } from '../../lib/supabaseClient';

type Report = {
  id: string;
  report_id: string;
  name: string;
  type: string;
  status: string;
  insurance_type?: string;
  risk_score?: number;
  estimated_min?: number;
  estimated_max?: number;
  user_name?: string;
  policies?: { name: string; insurer: string; premium: string }[];
  saving_tip?: string;
  report_date?: string;
  created_at: string;
};

const formatCurrency = (val: number) =>
  val >= 100000 ? `₹${(val / 100000).toFixed(1)}L` : `₹${(val / 1000).toFixed(0)}k`;

const statusStyle = (status: string) =>
  status === 'Ready' ? 'bg-green-50 text-green-700 border border-green-200' :
  status === 'Generating' ? 'bg-blue-50 text-blue-700 border border-blue-200' :
                            'bg-red-50 text-red-700 border border-red-200';

export const Reports = () => {
  const navigate = useNavigate();
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [openMenuId, setOpenMenuId] = useState<string | null>(null);
  const [previewReport, setPreviewReport] = useState<Report | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);

  /* ── Load from Supabase ── */
  useEffect(() => {
    const fetchReports = async () => {
      setLoading(true);
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) { setLoading(false); return; }

      const { data, error } = await supabase
        .from('reports')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (!error && data) setReports(data);
      setLoading(false);
    };
    fetchReports();
  }, []);

  /* ── Delete from Supabase ── */
  const handleDelete = async (id: string) => {
    setDeleting(id);
    const { error } = await supabase.from('reports').delete().eq('id', id);
    if (!error) setReports(prev => prev.filter(r => r.id !== id));
    setDeleting(null);
    setOpenMenuId(null);
  };

  /* ── Download HTML report ── */
  const handleDownload = (report: Report) => {
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>PolicyWise Report — ${report.name}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #1e293b; }
    h1 { color: #1E64FF; } h2 { color: #334155; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th { background: #f8fafc; text-align: left; padding: 10px; font-size: 13px; color: #64748b; }
    td { padding: 10px; border-bottom: 1px solid #f1f5f9; font-size: 14px; }
    .tip { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; margin-top: 16px; }
    .footer { margin-top: 40px; font-size: 12px; color: #94a3b8; text-align: center; }
  </style>
</head>
<body>
  <h1>🛡️ PolicyWise AI — Insurance Report</h1>
  <p><strong>Report ID:</strong> ${report.report_id || report.id.slice(0, 8).toUpperCase()} &nbsp;|&nbsp;
     <strong>Date:</strong> ${report.report_date || new Date(report.created_at).toLocaleDateString('en-IN')} &nbsp;|&nbsp;
     <strong>Name:</strong> ${report.user_name || 'N/A'}</p>
  <h2>Risk Profile</h2>
  <p><strong>Insurance Type:</strong> ${(report.insurance_type || 'N/A').toUpperCase()}</p>
  <p><strong>Risk Score:</strong> ${report.risk_score ?? 'N/A'}/100</p>
  ${report.estimated_min ? `<p><strong>Estimated Yearly Cost:</strong> ${formatCurrency(report.estimated_min)} – ${formatCurrency(report.estimated_max ?? 0)}</p>` : ''}
  ${report.policies?.length ? `
  <h2>Top Policy Recommendations</h2>
  <table>
    <thead><tr><th>#</th><th>Policy Name</th><th>Insurer</th><th>Yearly Premium</th></tr></thead>
    <tbody>${report.policies.map((p, i) => `<tr><td>${i+1}</td><td>${p.name}</td><td>${p.insurer}</td><td>${p.premium}</td></tr>`).join('')}</tbody>
  </table>` : ''}
  ${report.saving_tip ? `<div class="tip"><strong>💡 Money-Saving Tip</strong><br/>${report.saving_tip}</div>` : ''}
  <div class="footer">Generated by PolicyWise AI &nbsp;|&nbsp; For informational purposes only</div>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PolicyWise_${report.report_id || report.id.slice(0,8)}.html`;
    a.click();
    URL.revokeObjectURL(url);
    setOpenMenuId(null);
  };

  return (
    <div className="space-y-6">

      {/* Preview Modal */}
      {previewReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={() => setPreviewReport(null)}>
          <div className="absolute inset-0 bg-black/30 backdrop-blur-sm" />
          <div className="relative bg-white rounded-2xl shadow-2xl p-6 max-w-lg w-full z-10 max-h-[80vh] overflow-y-auto"
            onClick={e => e.stopPropagation()}>
            <h3 className="font-bold text-slate-900 text-lg mb-4">{previewReport.name}</h3>
            <div className="space-y-3 text-sm">
              <div className="grid grid-cols-2 gap-3">
                <div className="bg-slate-50 rounded-lg p-3">
                  <p className="text-slate-400 text-xs">Report ID</p>
                  <p className="font-medium">{previewReport.report_id || previewReport.id.slice(0,8).toUpperCase()}</p>
                </div>
                <div className="bg-slate-50 rounded-lg p-3">
                  <p className="text-slate-400 text-xs">Date</p>
                  <p className="font-medium">{previewReport.report_date || new Date(previewReport.created_at).toLocaleDateString('en-IN')}</p>
                </div>
                <div className="bg-slate-50 rounded-lg p-3">
                  <p className="text-slate-400 text-xs">Risk Score</p>
                  <p className="font-medium">{previewReport.risk_score ?? 'N/A'}/100</p>
                </div>
                <div className="bg-slate-50 rounded-lg p-3">
                  <p className="text-slate-400 text-xs">Est. Cost</p>
                  <p className="font-medium text-[#1E64FF]">
                    {previewReport.estimated_min
                      ? `${formatCurrency(previewReport.estimated_min)} – ${formatCurrency(previewReport.estimated_max ?? 0)}`
                      : 'N/A'}
                  </p>
                </div>
              </div>
              {previewReport.policies?.length ? (
                <div>
                  <p className="font-semibold text-slate-700 mb-2">Top Policies</p>
                  {previewReport.policies.map((p, i) => (
                    <div key={i} className="flex justify-between py-2 border-b border-slate-100 text-xs">
                      <span className="text-slate-700">{p.name} — {p.insurer}</span>
                      <span className="font-medium">{p.premium}</span>
                    </div>
                  ))}
                </div>
              ) : null}
              {previewReport.saving_tip && (
                <div className="bg-green-50 rounded-lg p-3">
                  <p className="text-green-700 text-xs">💡 {previewReport.saving_tip}</p>
                </div>
              )}
            </div>
            <div className="flex gap-3 mt-5">
              <button onClick={() => handleDownload(previewReport)}
                className="flex-1 border border-slate-200 text-slate-700 py-2.5 rounded-xl font-medium hover:bg-slate-50 flex items-center justify-center gap-2 text-sm">
                <Download className="w-4 h-4" /> Download
              </button>
              <button onClick={() => setPreviewReport(null)}
                className="flex-1 bg-[#1E64FF] text-white py-2.5 rounded-xl font-medium text-sm">
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 text-sm text-slate-400 mb-1">
            <span>Home</span> / <span className="text-slate-700">Reports</span>
          </div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">Reports</h1>
          <p className="text-slate-500 mt-1">Your saved insurance reports — synced across devices.</p>
        </div>
        <button onClick={() => navigate('/new-recommendation')}
          className="flex items-center gap-2 bg-[#1E64FF] text-white px-5 py-2.5 rounded-xl font-medium hover:bg-blue-700">
          <Plus className="w-4 h-4" /> New Report
        </button>
      </div>

      {/* Loading */}
      {loading ? (
        <div className="bg-white rounded-2xl border border-slate-200 p-12 flex flex-col items-center justify-center gap-3">
          <Loader2 className="w-8 h-8 text-[#1E64FF] animate-spin" />
          <p className="text-slate-500 text-sm">Loading your reports...</p>
        </div>
      ) : reports.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-200 p-16 text-center">
          <div className="w-16 h-16 bg-blue-50 rounded-full flex items-center justify-center mx-auto mb-4">
            <FileText className="w-8 h-8 text-[#1E64FF]" />
          </div>
          <h3 className="font-bold text-slate-900 text-lg mb-2">No reports yet</h3>
          <p className="text-slate-500 text-sm mb-6">Complete a recommendation to generate your first report.</p>
          <button onClick={() => navigate('/new-recommendation')}
            className="bg-[#1E64FF] text-white px-6 py-2.5 rounded-xl font-medium hover:bg-blue-700">
            Start New Recommendation
          </button>
        </div>
      ) : (
        <div className="bg-white rounded-2xl border border-slate-200">
          <div className="p-5 border-b border-slate-100 flex items-center justify-between">
            <h2 className="font-bold text-slate-900">Saved Reports ({reports.length})</h2>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-100">
                  <th className="text-left py-3 px-5 text-slate-500 font-medium">Report</th>
                  <th className="text-left py-3 px-4 text-slate-500 font-medium">Type</th>
                  <th className="text-left py-3 px-4 text-slate-500 font-medium">Risk Score</th>
                  <th className="text-left py-3 px-4 text-slate-500 font-medium">Est. Cost</th>
                  <th className="text-left py-3 px-4 text-slate-500 font-medium">Date</th>
                  <th className="text-left py-3 px-4 text-slate-500 font-medium">Status</th>
                  <th className="text-right py-3 px-5 text-slate-500 font-medium">Actions</th>
                </tr>
              </thead>
              <tbody>
                {reports.map(report => (
                  <tr key={report.id} className="border-b border-slate-50 hover:bg-slate-50 transition-colors">
                    <td className="py-3 px-5">
                      <div className="flex items-center gap-3">
                        <div className="p-2 bg-blue-50 text-[#1E64FF] rounded-lg shrink-0">
                          <FileText className="w-4 h-4" />
                        </div>
                        <div>
                          <p className="font-medium text-slate-900">{report.name}</p>
                          <p className="text-xs text-slate-400">{report.report_id || report.id.slice(0,8).toUpperCase()}</p>
                        </div>
                      </div>
                    </td>
                    <td className="py-3 px-4 text-slate-600 capitalize">{report.insurance_type || report.type}</td>
                    <td className="py-3 px-4">
                      {report.risk_score != null ? (
                        <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${
                          report.risk_score >= 70 ? 'bg-green-50 text-green-700' :
                          report.risk_score >= 45 ? 'bg-amber-50 text-amber-700' :
                                                   'bg-red-50 text-red-700'}`}>
                          {report.risk_score}/100
                        </span>
                      ) : '—'}
                    </td>
                    <td className="py-3 px-4 text-slate-600">
                      {report.estimated_min ? `${formatCurrency(report.estimated_min)} – ${formatCurrency(report.estimated_max ?? 0)}` : '—'}
                    </td>
                    <td className="py-3 px-4 text-slate-600">
                      {report.report_date || new Date(report.created_at).toLocaleDateString('en-IN')}
                    </td>
                    <td className="py-3 px-4">
                      <span className={`text-xs font-medium px-2.5 py-1 rounded-full ${statusStyle(report.status)}`}>
                        {report.status}
                      </span>
                    </td>
                    <td className="py-3 px-5 text-right relative">
                      <button onClick={() => setOpenMenuId(openMenuId === report.id ? null : report.id)}
                        className="p-1.5 hover:bg-slate-100 rounded-lg transition-colors">
                        {deleting === report.id
                          ? <Loader2 className="w-4 h-4 text-slate-500 animate-spin" />
                          : <MoreHorizontal className="w-4 h-4 text-slate-500" />}
                      </button>
                      {openMenuId === report.id && (
                        <div className="absolute right-6 top-8 z-20 bg-white border border-slate-200 rounded-xl shadow-lg py-1 w-44">
                          <button onClick={() => { setPreviewReport(report); setOpenMenuId(null); }}
                            className="w-full flex items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50">
                            <Eye className="w-4 h-4" /> View Preview
                          </button>
                          <button onClick={() => handleDownload(report)}
                            className="w-full flex items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50">
                            <Download className="w-4 h-4" /> Download
                          </button>
                          <button onClick={() => handleDelete(report.id)}
                            className="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50">
                            <Trash2 className="w-4 h-4" /> Delete
                          </button>
                        </div>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
};